import prescription_only from "../../Components/Assets/prescription_only.png";
import product from "../../Components/Assets/product.png";

export const ProductList = [
  {
    id: 0,
    image: prescription_only,
    name: "Advil (Ibuprofen)",
    rating: 5,
    price: 100,
    category: "tablet",
    isAvailable: true,
    isPrescriptionMed: true,
  },
  {
    id: 1,
    image: prescription_only,
    name: "Tylenol (Acetaminophen)",
    rating: 4,
    price: 95500,
    category: "tablet",
    isAvailable: true,
    isPrescriptionMed: true,
  },
  {
    id: 2,
    image: product,
    name: "Benadryl (Diphenhydramine)",
    rating: 5,
    price: 26.56,
    category: "tablet",
    isAvailable: true,
    isPrescriptionMed: false,
  },
  {
    id: 3,
    image: prescription_only,
    name: "Claritin (Loratadine)",
    rating: 5,
    price: 9000,
    category: "sprays",
    isAvailable: false,
    isPrescriptionMed: true,
  },
  {
    id: 4,
    image: prescription_only,
    name: "Pepto-Bismol ",
    rating: 3,
    price: 180,
    category: "inhalers",
    isAvailable: false,
    isPrescriptionMed: true,
  },
  {
    id: 5,
    image: prescription_only,
    name: "Tums",
    rating: 4,
    price: 1890,
    category: "tablet",
    isAvailable: true,
    isPrescriptionMed: true,
  },
  {
    id: 6,
    image: prescription_only,
    name: "Zyrtec",
    rating: 5,
    price: 360,
    category: "injections",
    isAvailable: true,
    isPrescriptionMed: true,
  },
  {
    id: 7,
    image: product,
    name: "Nexium ",
    rating: 5,
    price: 100020,
    category: "capsules",
    isAvailable: true,
    isPrescriptionMed: false,
  },
  {
    id: 8,
    image: prescription_only,
    name: "Allegra",
    rating: 1,
    price: 180,
    category: "tablet",
    isAvailable: false,
    isPrescriptionMed: true,
  },
  {
    id: 9,
    image: product,
    name: "Benadryl (Diphenhydramine)",
    rating: 5,
    price: 5500,
    category: "capsules",
    isAvailable: true,
    isPrescriptionMed: false,
  },
  {
    id: 10,
    image: product,
    name: "Lipitor",
    rating: 5,
    price: 100,
    category: "tablet",
    isAvailable: false,
    isPrescriptionMed: false,
  },
  {
    id: 11,
    image: prescription_only,
    name: "Ambien (Zolpidem)",
    rating: 4,
    price: 10090,
    category: "liquid",
    isAvailable: true,
    isPrescriptionMed: true,
  },
  {
    id: 12,
    image: product,
    name: "Prevacid",
    rating: 2,
    price: 100,
    category: "liquid",
    isAvailable: true,
    isPrescriptionMed: false,
  },
];
