import prescription_only from "../../Components/Assets/prescription_only.png";
import product from "../../Components/Assets/product.png";

export const ProductList = [
  {
    id: 0,
    image: prescription_only,
    name: "PRODUCT NAME1",
    rating: 5,
    price: 1000,
    isAvailable: true,
    isPrescriptionMed: true,
  },
  {
    id: 1,
    image: prescription_only,
    name: "oxine",
    rating: 4,
    price: 500,
    isAvailable: true,
    isPrescriptionMed: true,
  },
  {
    id: 2,
    image: product,
    name: "PRODUCT NAME3",
    rating: 5,
    price: 1000,
    isAvailable: true,
    isPrescriptionMed: false,
  },
  {
    id: 3,
    image: prescription_only,
    name: "PRODUCT NAME4",
    rating: 5,
    price: 1000,
    isAvailable: false,
    isPrescriptionMed: true,
  },
  {
    id: 4,
    image: prescription_only,
    name: "PRODUCT NAME5",
    rating: 5,
    price: 1000,
    isAvailable: false,
    isPrescriptionMed: true,
  },
  {
    id: 5,
    image: prescription_only,
    name: "PRODUCT NAME6",
    rating: 5,
    price: 1000,
    isAvailable: true,
    isPrescriptionMed: true,
  },
  {
    id: 6,
    image: prescription_only,
    name: "PRODUCT NAME7",
    rating: 5,
    price: 1000,
    isAvailable: true,
    isPrescriptionMed: true,
  },
  {
    id: 7,
    image: product,
    name: "PRODUCT NAME8",
    rating: 5,
    price: 1000,
    isAvailable: true,
    isPrescriptionMed: false,
  },
  {
    id: 8,
    image: prescription_only,
    name: "PRODUCT NAME9",
    rating: 5,
    price: 1000,
    isAvailable: false,
    isPrescriptionMed: true,
  },
  {
    id: 9,
    image: product,
    name: "PRODUCT NAME10",
    rating: 5,
    price: 1000,
    isAvailable: true,
    isPrescriptionMed: false,
  },
  {
    id: 10,
    image: product,
    name: "PRODUCT NAME11",
    rating: 5,
    price: 1000,
    isAvailable: false,
    isPrescriptionMed: false,
  },
  {
    id: 11,
    image: prescription_only,
    name: "PRODUCT NAME12",
    rating: 5,
    price: 1000,
    isAvailable: true,
    isPrescriptionMed: true,
  },
  {
    id: 12,
    image: product,
    name: "PRODUCT NAME13",
    rating: 5,
    price: 1000,
    isAvailable: true,
    isPrescriptionMed: false,
  },
];
